<!-- Section 2 -->
<section id="section2" class="about">
    <div class="container">
        <!-- Title row -->
        <div class="row">
            <div class="col-md-12 big-title ">
                <h2>Estamos para atenderte</h2>
            </div>
            <div class="clearfix"></div>
            <div class="col-md-12 sub-title text-center ">
                <!--<h3>Imag&iacute;nate ver tus videos de alta definici&oacute;n sin cortes ni esperas, descargar tu m&uacute;sica favorita en segundos, que toda la familia pueda navegar en simult&aacute;neo y sin interrupciones. </h3>-->
                <h3>Revisa las preguntas frecuentes o comunícate con nosotros.</h3>
                <!-- Portfolio Filters -->   
                <div id="filters">

                    <ul class="clearfix">
                        <li><a href="#" ><h5>Escr&iacute;benos</h5></a></li> 
                        <li><a href="#" ><h5>Ll&aacute;manos</h5></a></li>
                        <li><a href="#" ><h5>Preguntas frecuentes</h5></a></li>
                    </ul>
                </div>
                <!-- /Portfolio Filters -->
            </div>
        </div>
        <!-- /Title row -->
        <?php $this->getMesseger();?>
    </div>
    
    <!-- Contact form -->
    <div class="contact-form">
        <div class="container">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Escr&iacute;benos</h2>
                </div>
                <div class="clearfix"></div>
            </div>
            <!-- /Title row -->
            <!-- Form element row -->
            <div class="row text-center">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <form action="/soporte" method="post" name="soporte">
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input class="form-control" id="name" name="Name" type="text" placeholder="Nombres y apellidos" value="" required><br>
                                        </div>
                                        <div class="col-md-12">
                                            <input class="form-control" type="email" id="email" name="Email" placeholder="Email" value="" required><br>
                                        </div>
                                        <div class="col-md-12">
                                            <input class="form-control" type="text" id="phone" name="Phone" placeholder="Teléfono" value="" required><br>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <textarea class="form-control" id="subject" name="Subject" rows="8" cols="40" placeholder="Mensaje" required></textarea><br>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 ">
                                    <button type="submit" class="btn btn-2 btn-2c">Enviar</button>
                                    <!--<div class="success alert-success alert" style="display:none">Su mensaje fue enviado con &eacute;xito.</div>-->
                                    <div class="error alert-danger alert" style="display:none">Su cuenta de E-mail debe ser v&aacute;lida y su mensaje mayor a 100 caracteres.</div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
                <div class="col-md-2"></div>
            </div>
            <!-- /Form element row -->
        </div>
    </div>
    <!-- /Contact form -->
    <!-- What we do best -->
    <div class="skills-wrap">
        <div class="container">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Ll&aacute;manos</h2>
                </div>

                <div class="clearfix"></div>

                <div class="col-md-12 sub-title text-center ">
                    <h3>De lunes a viernes de 9:00 am a 6:00 pm.</h3>
                    <h2>729 0000</h2>

                </div>

            </div>
            <!-- /Title row -->
            <hr>
        </div>
    </div>
    <!-- /What we do best -->
    <!-- What we do best -->
    <div class="skills-wrap">
        <div class="container">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Preguntas frecuentes</h2>
                </div>
                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p1"><h3>¿Qué ofrece VOY?</h3></a></div><div id="p1" class="accordion-body collapse"><div class="accordion-inner"><p>VOY ofrece una velocidad de conexión a internet de 100 Megabits por segundo, mucho más rápida que el promedio de banda ancha en el país. Para brindar el servicio VOY lleva una conexión de fibra óptica hasta tu hogar. </p></div></div></div>

                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p2"><h3>¿Qué es un megabit?</h3></a></div><div id="p2" class="accordion-body collapse"><div class="accordion-inner"><p>Un megabit por segundo (Mbps) es una conexión de 1,000 kilobits por segundo (Kbps). 100 megabits por segundo es la conexión a internet más rápida del Perú hoy en día, permitiéndote obtener lo que desees instantáneamente. Ya no tendrás que esperar a que carguen las cosas, todo estará listo cuando tú lo estés. Entonces, si estás en una video llamada, cargando videos personales, o jugando en línea, todo lo que necesitas hacer es un clic y listo.</p></div></div></div>                


                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p3"><h3>¿Cómo obtengo el servicio de VOY en mi casa?</h3></a></div><div id="p3" class="accordion-body collapse"><div class="accordion-inner"><p>Estamos construyendo nuestra red de fibra óptica VOY por demanda. Los vecinos de una zona, edificio o condominio que hagan más reservas serán los primeros en obtener el servicio VOY. Así es como funciona:
                            <ul>
                                <li>Comprueba si tu dirección tiene cobertura<br/><br/></li>
                                <li>Solicita tu plan<br/><br/></li>
                                <li>Espera a que te contactemos<br/><br/></li>
                                <li>Programa tu instalación<br/><br/></li>
                                <li>Disfruta<br/><br/></li>
                            </ul></p></div></div></div>

                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p4"><h3>¿Cómo deciden si instalarán su red de fibra óptica en mi zona?</h3></a></div><div id="p4" class="accordion-body collapse"><div class="accordion-inner"><p>La cantidad de reservas requeridas por zona varía entre 5% y 25% de los hogares de dicha zona.</p></div></div></div>

                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p5"><h3>¿VOY tiene un producto para empresas?</h3></a></div><div id="p5" class="accordion-body collapse"><div class="accordion-inner"><p>Actualmente estamos enfocados en nuestra red de Fibra óptica hasta el hogar, que es para usuarios residenciales. Para obtener el servicio para empresas por favor solicite el contacto de uno de nuestros asesores corporativos.</p></div></div></div>

                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p6"><h3>¿Puedo llamar a VOY para obtener ayuda?</h3></a></div><div id="p6" class="accordion-body collapse"><div class="accordion-inner"><p>¡Por supuesto! Por favor escriba o llame al 729-0000 si tiene alguna consulta.</p></div></div></div>

                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p7"><h3>¿Podré usar WiFi con VOY?</h3></a></div><div id="p7" class="accordion-body collapse"><div class="accordion-inner"><p>Sí. Nuestro router óptico incluye WiFi, diseñado para darte acceso a VOY en tu hogar.</p></div></div></div>

                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p8"><h3>¿Será mi conexión WiFi tan rápida como una conexión por cable?</h3></a></div><div id="p8" class="accordion-body collapse"><div class="accordion-inner"><p>No. WiFi es más lenta que una conexión con cable. Sin embargo, la tecnología WiFi de nuestro router óptico te brindará una gran conectividad.</p></div></div></div>

                <div class="accordion-group"><div class="accordion-heading blightblue"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#p9"><h3>¿Existe algún límite en la cantidad de datos enviados o recibidos?</h3></a></div><div id="p9" class="accordion-body collapse"><div class="accordion-inner"><p>¡De ninguna manera! Queremos que uses y disfrutes de tu conexión de internet. No hay límites o restricciones en la cantidad de datos que puedes enviar o recibir.</p></div></div></div>      

            </div>
            <!-- /Title row -->
            <hr>

        </div>
    </div>
    <!-- /What we do best -->
</section>