<html>
    <head>
        <title>Nuevo contrato TELEONIA</title>
    </head>
    <body>
    <u>Nuevo servicio de <?= $this->mailData['plan']; ?> :</u> 
    <br>&nbsp;
    <div> Plan : <?= $this->mailData['plan']; ?> </div>
    <div> Tipo : <?= $this->mailData['tipo']; ?> </div>
    <div> Estado : <?php echo $this->mailData['estado']; ?> </div>
    <div> Telefon&iacute;a : <?php echo $this->mailData['telefonia']; ?>  </div>
    <div> Nombre : <?= $this->mailData['nombre']; ?> </div>
    <div> Apellido : <?= $this->mailData['apellido']; ?> </div>
    <div> Documento : <?= $this->mailData['documento']; ?> </div>
    <div> Direcci&oacute;n : <?= $this->mailData['direccion']; ?> </div>
    <div> Distrito : <?= $this->mailData['distrito']; ?> </div>
    <div> Fijo : <?= $this->mailData['fijo']; ?> </div>
    <div> M&oacute;vil : <?= $this->mailData['celular']; ?> </div>
    <div> Correo : <?= $this->mailData['correo']; ?> </div>
</body>
</html>