<html>
    <head>
        <title>Nuevo Predio para Verificación</title>
    </head>
    <body>
    <u>Nuevo Predio para Verificación N° <?= $this->mailData['predio']; ?></u> 
    <br>&nbsp;
    <div> Predio N° : <?= $this->mailData['predio']; ?> </div>
    <div> Tipo : <?= $this->mailData['tipo']; ?> </div>
    <div> Plan : <?= $this->mailData['plan']; ?> </div>
    <div> Direcci&oacute;n : <?php echo $this->mailData['direccion']; ?> </div>
    <div> Distrito : <?php echo $this->mailData['distrito']; ?> </div>
</body>
</html>