<html>
    <head>
        <title>Nueva Registro</title>
    </head>
    <body>
    <u>Datos de contacto :</u> 
    <br>&nbsp;
    <div> Nombre : <?php echo $this->mailData['nombre']; ?> </div>
    <div> Apellido : <?php echo $this->mailData['apellido']; ?> </div>
    <div> Correo : <?php echo $this->mailData['correo']; ?> </div>
    <div> Direccion : <?php echo $this->mailData['direccion']; ?> </div>
    <div> Tel&eacute;fono : <?php echo $this->mailData['celular']; ?> </div>
</body>
</html>