<html>
    <head>
        <title>Nueva solicitud de soporte</title>
    </head>
    <body>
    <u>Datos de contacto :</u> 
    <br>&nbsp;
    <div> Nombre : <?php echo $this->mailData['Name']; ?> </div>
    <div> Correo : <?php echo $this->mailData['Email']; ?> </div>
    <div> Tel&eacute;fono : <?php echo $this->mailData['Phone']; ?> </div>
    <div> Mensaje : <?php echo $this->mailData['Subject']; ?> </div>
</body>
</html>