<!-- Section 1 -->
<section id="section1" class="clients">
    <div class="testimonial-wrap">
        <div class="texture-layer">
            <div class="container">
                <!-- Title row -->
                <div class="row">
                    <div class="col-md-12 big-title light  ">
                        <h2>Voy fibra &oacute;ptica</h2>
                    </div>

                    <div class="clearfix"></div>

                    <div class="col-md-12 sub-title text-center light  ">
                        <h3>Voy ofrece la conexi&oacute;n a internet m&aacute;s r&aacute;pida del pa&iacute;s. Descargas instant&aacute;neas. Internet sin l&iacute;mites y telefonía fija digital.</h3>
                        <p align="center"><a href="#section2" class="btn btn-2 btn-2c">Ver m&aacute;s</a></p>


                    </div>
                </div>
                <!-- /Title row -->

            </div>
        </div>
    </div>

</section>
<!-- /Section 1 -->


<!-- Section 2 -->
<section id="section2" class="about">
    <div class="container">
        <!-- Title row -->
        <div class="row">
            <div class="col-md-12 big-title  ">
                <h3>Vive hoy la mejor experiencia en internet.</h3>
            </div>

            <div class="clearfix"></div>

            <div class="col-md-12 sub-title text-center  ">
                <!--<h3>Imag&iacute;nate ver tus videos de alta definici&oacute;n sin cortes ni esperas, descargar tu m&uacute;sica favorita en segundos, que toda la familia pueda navegar en simult&aacute;neo y sin interrupciones. </h3>-->
                <h3>Imagínate ver tus videos de alta definición sin cortes ni esperas, descargar tu música favorita en segundos, que toda la familia pueda navegar en simultáneo sin interrupciones.</h3>


                <!-- Portfolio Filters -->   
                <div id="filters">

                    <ul >
                        <li><a href="#section3" ><h5>Super velocidad</h5></a></li> 
                        <li><a href="#" ><h5>Wi-Fi potente</h5></a></li>
                        <li><a href="#" ><h5>Descargas ilimitadas</h5></a></li>
                        <li><a href="#" ><h5>Sin permanencia</h5></a></li>
                        <li><a href="#" ><h5>Conexiones simultáneas</h5></a></li>
                    </ul>
                </div>
                <!-- /Portfolio Filters -->

            </div>
        </div>

        <!-- /Title row -->

    </div>

</section>
<!-- /Section 2 -->


<!-- What we do best -->
<div class="skills-wrap">
    <div class="container">

        <!-- Section 3 -->
        <section id="section3" class="clients">

            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title  ">
                    <h2>Super Velocidad</h2>
                </div>

                <div class="clearfix"></div>

                <div class="col-md-12 sub-title text-center  ">
                    <h3>Hasta 100 Mbps. Voy ofrece la conexión a internet m&aacute;s r&aacute;pida del pa&iacute;s, permitiendo descargar lo que desees al instante. Ya no tienes que esperar a que las cosas terminen de descargar para verlas, todo estar&aacute; listo cuando tu lo quieras. Ahora podr&aacute;s usar el chat con video, jugar en l&iacute;nea, subir fotos y ver videos, todo en simult&aacute;neo.</h3>
                </div>

                <p align="center"><a href="planes" class="btn btn-2 btn-2c">Lo quiero</a></p>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <!--
                                                                    <p align="center"><img align="center" src="img/voy.ookla.png" alt="Mide tu velocidad" class="img-responsive"></p>
                                                            <br>
                        -->
                        <br>
                        <p align="center"><a href="/medidor" class="btn btn-2 btn-2c">Mide tu velocidad con tu operador actual</a></p>

                    </div>
                </div>

            </div>
            <!-- /Title row -->
            <hr><br>

            </div>
            </div>



            <!-- Section 4 -->
            <section id="section4" class="clients">


                <!-- Title row -->
                <div class="row">
                    <div class="col-md-12 big-title  ">
                        <h2>Wi-Fi Potente</h2>
                    </div>

                    <div class="clearfix"></div>

                    <div class="col-md-12 sub-title text-center wow ">

                        <h3>Disfruta de velocidades Wi-Fi super r&aacute;pido con 802.11a/b/g/n. Extiende tu acceso a Voy fibra &oacute;ptica en tu hogar con el punto de acceso Wi-Fi integrado en tu router &oacute;ptico.</h3>
                    </div>

                    <p align="center"><a href="planes" class="btn btn-2 btn-2c">Lo quiero</a></p>

                </div>
                <!-- /Title row -->
                <hr><br>

            </section>
            <!-- /Section 4 -->

            <!-- Section 5 -->
            <section id="section5" class="clients">

                <!-- Title row -->
                <div class="row">
                    <div class="col-md-12 big-title  ">
                        <h2>Descargas ilimitadas</h2>
                    </div>

                    <div class="clearfix"></div>

                    <div class="col-md-12 sub-title text-center   ">

                        <h3>Internet es para todos y por eso debemos disfrutarlo sin límites, Voy fibra &oacute;ptica te ofrece la conexión a internet más rápida del país, descarga todo lo que quieras y no te preocupes pues no necesitas un plan de datos, simplemente tu internet con Voy nunca se acaba.</h3>


                    </div>

                    <p align="center"><a href="planes" class="btn btn-2 btn-2c">Lo quiero</a></p>

                </div>
                <!-- /Title row -->
                <hr><br>

            </section>
            <!-- /Section 5 -->

            <!-- Section 6 -->
            <section id="section6" class="clients">

                <!-- Title row -->
                <div class="row">
                    <div class="col-md-12 big-title   ">
                        <h2>Sin contrato de permanencia</h2>
                    </div>

                    <div class="clearfix"></div>

                    <div class="col-md-12 sub-title text-center   ">
                        <h3>Olvídate de los contratos a plazo forzoso, queremos que nos elijas por nuestro servicio y no por que tienes un contrato que cumplir. Con Voy fibra &oacute;ptica puedes contratar el servicio y si no satisface tus expectativas podrás cancelarlo en cualquier momento. </h3>
                    </div>

                    <p align="center"><a href="planes" class="btn btn-2 btn-2c">Lo quiero</a></p>

                </div>
                <!-- /Title row -->
                <hr><br>

            </section>
            <!-- /Section 6 -->

            <!-- Section 7 -->
            <section id="section7" class="clients">

                <!-- Title row -->
                <div class="row">
                    <div class="col-md-12 big-title   ">
                        <h2>Conexiones simult&aacute;neas</h2>
                    </div>

                    <div class="clearfix"></div>

                    <div class="col-md-12 sub-title text-center   ">
                        <h3>Disfruta con los tuyos de la mejor experiencia multimedia con los 100 Mbps de Voy fibra &oacute;ptica. No sólo podrás descargar y compartir tus archivos a una velocidad extremadamente rápida, sino que toda la familia podrá disfrutar a la vez conectados desde diferentes dispositivos, sin causar interrupciones en el servicio ni experimentar una pérdida de calidad. Sin duda la mejor opción para ti y lo tuyos.</h3>
                    </div>

                    <p align="center"><a href="planes" class="btn btn-2 btn-2c">Lo quiero</a></p>

                </div>
                <!-- /Title row -->

            </section>
            <!-- /Section 7 -->
            <hr>