<!-- Section 4 -->
<section id="section4" class="services">
    <div class="service-wrap">
        <div class="container">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Contratos, normas y condiciones</h2>
                </div>
                <!--<div class="clearfix"></div>
                <div class="col-md-12 sub-title text-center wow slideInRight">
                      <h3>We match the project goals with a proposed solution considering latest web features, web design and corporate branding!</h3>
                </div>-->
            </div>
            <!-- /Title row -->
            <!-- Service row 1 -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
                    <div class="service-box">
                        <div class="service-icon">
                            <i class="fa fa-arrows-alt"></i>
                        </div>
                        <div class="service-box-content">
                            <h4>Contratos</h4>
                            <ul>
                                <li><a target="_blank" href="documentos/Contrato-de-Prestacion-de-Servicios-VOY-5.42-MARCO.pdf">Contrato</a></li>
                                <li><a target="_blank" href="documentos/Contrato-de-Prestacion-de-Servicios-VOY-5.42-ANEXO.pdf">Anexo del contrato</a></li>
                                <li><a>Portabilidad de telefon&iacute;a</a></li>
                            </ul>     
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
                    <div class="service-box">
                        <div class="service-icon">
                            <i class="fa fa-eye"></i>
                        </div>
                        <div class="service-box-content">
                            <h4>Normas legales</h4>
                            <ul>
                                <li><a target="_blank" href="documentos/Condiciones.pdf">Condiciones de Uso</a></li>
                                <li><a target="_blank" href="documentos/Directiva.pdf">Directiva de reclamos</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
                    <div class="service-box">
                        <div class="service-icon">
                            <i class="fa fa-edit"></i>
                        </div>
                        <div class="service-box-content">
                            <h4>Formularios</h4>
                            <ul>
                                <li><a target="_blank" href="documentos/formularios/Formulario-de-Queja.pdf">Formulario de Queja</a></li>
                                <li><a target="_blank" href="documentos/formularios/Formulario-de-Reclamo.pdf">Formulario de Reclamo</a></li>
                                <li><a target="_blank" href="documentos/formularios/Formulario-de-Apelacion.pdf">Formulario de Recurso de Apelaci&oacute;n</a></li>
                                <li><a target="_blank" href="documentos/formularios/Formulario-de-Reconsideracion.pdf">Formulario de Reconsideraci&oacute;n</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Service row 1 -->
        </div>
    </div>
</section>
<!-- /Section 4 -->