
<!-- CONTENIDO inicio -->

<!-- Section 6 -->
<section id="section6" class="pricing">
    <div class="container">
        <div class="row flat">

            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title wow ">
                    <h2>Mide tu Velocidad con tu operador actual</h2>
                </div>

                <div class="clearfix"></div>

            </div>
            <!-- /Title row -->



            <!-- Content starts -->
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                            <div align="center"  >
                                <!--                                <object type="text/html" data="http://speedtest.voy.pe/"  
                                                                        class="skrollable skrollable-between"
                                                                        style="height: 420px; width: 620px">
                                
                                                                </object>-->

                                <iframe src="http://speedtest.voy.pe/" width="630" frameborder="0" height="570" scrolling="no" 
                                        style="margin-top: 0px;   overflow: hidden">

                                </iframe>
                            </div>

                            <!-- Title row -->
                            <div class="row">
                                <div class="col-md-12 big-title  ">
                                    <h2>Solicita la super velocidad Voy</h2>
                                </div>

                                <div class="clearfix"></div>

                                <div class="col-md-12 sub-title text-center wow ">
                                    <a href="contratar" class="btn btn-2 btn-2c">Lo quiero</a>

                                </div>

                            </div>
                            <!-- /Title row -->



                        </div>
                    </div>
                    </section>
                    <!-- /Section 6 -->


