<!-- Section 4 -->
<section id="section4" class="services">
    <div class="service-wrap">
        <div class="container">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Formas de pago</h2>
                </div>

                <!--<div class="clearfix"></div>

                <div class="col-md-12 sub-title text-center wow slideInRight">
                      <h3>We match the project goals with a proposed solution considering latest web features, web design and corporate branding!</h3>
                </div>-->
            </div>
            <!-- /Title row -->

            <!-- Service row 1 -->
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
                    <div class="service-box">
                        <div class="service-box-content">
                            <p><img src="<?php echo STATIC_URL ?>voy/img/ViaBCP.png"></p><br>

                            <h4>Banco de Cr&eacute;dito del Per&uacute;</h4>
                            <br>
                            <p>Por ventanilla:</p> 
                            <p>Utiliza el número de documento de identidad del titular del servicio como referencia para el pago.</p>
                            <br>
                            <p>Por la página WEB nos encuentra en:</p>
                            <ul>
                                <li>1. Pagos y Transferencias 	</li>
                                <li>2. Pago de Servicios 		</li>
                                <li>3. Telecomunicaciones 		</li>
                                <li>4. Voy - Moche Inversiones 	</li>
                                <li>5. Servicios públicos		</li>
                                <li>El número de referencia es el documento de identidad del titular del servicio</li>
                            </ul>     
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ">
                    <div class="service-box">
                        <div class="service-box-content">
                            <p><img src="<?php echo STATIC_URL ?>voy/img/scotiabank.png"></p><br>

                            <h4>Scotiabank</h4>
                            <br>
                            <p>Por ventanilla:</p> 
                            <p>Utiliza el número de documento de identidad del titular del servicio como referencia para el pago.</p>
                            <br>
                            <p>Por la página WEB nos encuentra en:</p>
                            <ul>
                                <li>1. Pagos 				 		</li>
                                <li>2. Teléfono, cable e internet 	</li>
                                <li>3. Voy - Moche Inversiones 		</li>
                                <li>El número de referencia es el documento de identidad del titular del servicio</li>
                            </ul>     
                        </div>
                    </div>
                </div>
            </div>
            <!-- Service row 1 -->

        </div>
    </div>
</section>