<!-- Section 6 -->
<section id="section6" class="pricing">
    <div class="container">
        <div class="row flat">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Planes</h2>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12 sub-title text-center ">
                    <!-- <h3>What you have become is the price you paid to get what you used to want!</h3>-->
                </div>
            </div>
            <!-- /Title row -->
            <!-- Plan -->
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <a href="residencial">
                    <ul class="plan plan3" style="background-image: url(/static/voy/img/residenciales.jpg) ;">
                        <li class="plan-name">
                            Residencial
                        </li>
                    </ul></a>
            </div>
            <!-- /Plan -->
            <!-- Plan -->
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <a href="negocios">
                    <ul class="plan plan3" style="background-image: url(/static/voy/img/negocios.jpg) ;">
                        <li class="plan-name">
                            Negocios
                        </li>
                    </ul></a>
            </div>
            <!-- /Plan -->
            <!-- Plan -->
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <a href="empresas">
                    <ul class="plan plan3" style="background-image: url(/static/voy/img/empresas.jpg);">
                        <li class="plan-name">
                            Empresas
                        </li>
                    </ul></a>
            </div>
            <!-- /Plan -->
        </div>
    </div>
</section> 
<style>
    .flat .plan li.plan-name {
        /*margin-bottom:20px;*/
        bottom:0px;
        position:absolute;
        background-color:rgba(34, 34, 34, 0.5);
        transition:background 0.3s ease;
    }
   .flat .plan{
        background-size: 100%;   
        height:180px
    }
</style>
