
<h3 class="admin-title"><?php echo $this->element->getView()->titulo?></h3>
   <div class="alert alert-info">
   <span style="color:red;"><?php $this->getMesseger();?></span>
   </div>  
<div class="frm-panel">
    <form id="frm-article" action="<?php echo $this->element->getView()->action?>" 
          method="post" Enctype="multipart/form-data">
        <div class="control-group">
            <label class="control-label" for="login">Usuario:</label>
            <div class="controls">
                <?php echo $this->element->login; ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="name">Nombre:</label>
            <div class="controls">
                <?php echo $this->element->name; ?>
                <?php echo $this->element->iduser; ?> 
            </div>
	</div>
         <div class="control-group">
            <label class="control-label" for="apepat">Apellido Paterno:</label>
            <div class="controls">
                <?php echo $this->element->apepat; ?>
            </div>
	</div>
          <div class="control-group">
            <label class="control-label" for="apemat">Apellido Materno:</label>
            <div class="controls">
                <?php echo $this->element->apemat; ?>
            </div>
	</div>
	<div class="control-group last">
            <div class="control">
                <button class="btn-admin" type="submit">Guardar</button>
            </div>
	</div>
   </form>
</div>