<h3 class="admin-title">Listado de Roles</h3>
<div class="alert alert-info"><span style="color:red;"><?php $this->getMesseger(); ?></span>
</div>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Roles</h2>
        <a class="btn-admin" title="Nuevo Rol" href="/admin/role/new">Nuevo Rol</a>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>