<h3 class="admin-title">Listado de Usuarios</h3>
<?php $this->getMesseger(); ?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Usuario</h2>
        <a class="btn-admin" title="Nuevo Usuario" href="/admin/usuarios/new">Nuevo Usuario</a>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Rol</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>