<section id="section6" class="pricing">
    <div class="container">
        <div class="row flat">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title  ">
                    <h2>Pagar-Pasarela</h2>
                </div>
                <div class="col-md-8">
                    <form action="/pagar-pasarela" method="post" name="contratar">
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12  ">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="radio" name="medio" value="visa" checked>ViSA 
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12   ">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="radio" name="medio" value="mastercard">MASTERCARD
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 ">
                                        <button type="submit" class="btn btn-2 btn-2c">PAGAR</button>
                                        <!--<div class="success alert-success alert" style="display:none">-->
                                        <!--Su solicitud fue enviada con &eacute;xito.-->
                                        <!--</div>-->
                                        <div class="error alert-danger alert" style="display:none">
                                            Debe completar todos los datos y su cuenta de E-mail debe ser v&aacute;lida.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>