<!-- Section 6 -->
<section id="section6" class="pricing">
    <div class="container">
        <div class="row flat">
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Resultado Master Card</h2>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12 sub-title text-center ">
                </div>
            </div>
            <div class="col-md-12 sub-title text-center ">
                <ul class="plan plan3" >
                    <li class="plan-name">
                        MENSAJE
                    </li>
                    <li>
                       O1:  <?php echo $this->respuesta['O1']; ?>
                    </li>
                    <li>
                       O3 : <?php echo $this->respuesta['O3']; ?>
                    </li>
                    <li>
                       O8:  <?php echo $this->respuesta['O8']; ?>
                    </li>
                    <li>
                       O9:  <?php echo $this->respuesta['O9']; ?>
                    </li>
                    <li>
                      O10:   <?php echo $this->respuesta['O10']; ?>
                    </li>
                    <li>
                      O11:   <?php echo $this->respuesta['O11']; ?>
                    </li>
                    <li>
                      O12:  <?php echo $this->respuesta['O13']; ?>
                    </li> <li>
                     O16:    <?php echo $this->respuesta['O16']; ?>
                    </li>
                    <li>
                     O17:   <?php echo $this->respuesta['O17']; ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>