<!-- Section 6 -->
<section id="section6" class="pricing">
    <div class="container">
        <div class="row flat">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title ">
                    <h2>Resultado</h2>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12 sub-title text-center ">
                    <!-- <h3>What you have become is the price you paid to get what you used to want!</h3>-->
                </div>
            </div>
            <!-- /Title row -->
            <!-- Plan -->

            <div class="col-md-12 sub-title text-center ">
                <ul class="plan plan3" >
                    <li class="plan-name">
                        <?php
                        if ($this->respuestaVisa["cantidad_operaciones"] < 2) {
                            echo $this->respuestaVisa["cantidad_operaciones"] . ' Operacion';
                        } else {
                            echo $this->respuestaVisa["cantidad_operaciones"] . ' Operaciones';
                        }
                        ?>
                    </li>
                    <li>
                        <?= 'Codigo De Orden :     ' . $this->respuestaVisa["resultado"][1]["Nordent"]; ?>
                    </li>
                    <li>
                        <?= 'Nombre :    ' . $this->respuestaVisa["resultado"][1]["Nombre_th"]; ?>
                    </li>

                    <li>
                        <?= 'Costo :    ' . $this->respuestaVisa["resultado"][1]["Imp_autorizado"]; ?>
                    </li>
                    <li>
                        <?= 'Estado :    ' . $this->respuestaVisa["resultado"][1]["Estado"]; ?>
                    </li>
                    <li>
                        <?= 'Fecha y hora :   ' . $this->respuestaVisa["resultado"][1]["Fechayhora_tx"]; ?>
                    </li>
                </ul>
            </div>
            <?php
            if ($this->respuestaVisa["cantidad_mensajes"] > 0) {
                ?>
                <div class="col-md-12 sub-title text-center ">
                    <ul class="plan plan3" >
                        <li class="plan-name">
                            Mensaje Error 
                        </li>
                        <li>
                            <?= $this->respuestaVisa["mensaje"]; ?>
                        </li>
                    </ul>
                </div>
                <?php
            }
            ?>

        </div>
    </div>
</section>