<section id="section6" class="pricing">
    <div class="container">
        <div class="row flat">
            <!-- Title row -->
            <div class="row">
                <div class="col-md-12 big-title  ">
                    <h2>Empresas</h2>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12 sub-title text-center ">
                    <!--<h3>Imag&iacute;nate ver tus videos de alta definici&oacute;n sin cortes ni esperas, descargar tu m&uacute;sica favorita en segundos, que toda la familia pueda navegar en simult&aacute;neo y sin interrupciones. </h3>-->
                    <h3><?= $this->TipoPlan ?></h3>
                </div>
            </div>
            <!-- /Title row -->
            <?php $this->getMesseger(); ?>
            <br>
            <div class="col-lg-4 col-md-4 col-sm-4 hidden-xs">
                <ul class="plan plan3" >
                    <li class="plan-name">
                        <?= $this->DetallePlan['nombre'] ?>
                    </li>
                    <li class="plan-price">
                    </li>
                    <?php
                    $descripcion = explode("|", $this->DetallePlan['descripcion']);
                    foreach ($descripcion as $valor) {
                        ?>
                        <li><?= $valor ?></li>
                    <?php } ?>
                    <li>Válido hasta el <?= $this->fecha; ?>
                    </li>
                </ul>
            </div>
            <!-- Contact form -->
            <div class="contact-form">
                <!-- Form element row -->

                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <form action="/empresas" method="post" name="corporativo">
                        <fieldset>
                            <div class="row">

                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12  ">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12  ">
                                            <ul class="plan plan3" >
                                                <li class="plan-name">
                                                    Lo Quiero
                                                </li>
                                                <li class="plan-price">
                                                    Déjanos tus datos de contacto y te llamaremos en cuanto puedas contratar nuestros servicios.
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12  ">
                                            <input name="plan" type="hidden" value="<?= $this->DetallePlan['codigo'] ?>" >
                                            <input class="form-control" id="lastname" name="razonSocial" type="text" placeholder="Razon Social" value="" required>
                                            <br>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12  ">
                                            <input class="form-control" id="lastname" name="numeroRUC" type="number" placeholder="Número RUC" value="" required>
                                            <br>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12  ">
                                            <input class="form-control" id="lastname" name="nombreContacto" type="text" placeholder="Nombre de Contacto" value="" required>
                                            <br>
                                        </div>

                                        <!--                                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12  ">
                                                                                    <input class="form-control" id="name" name="nombreContacto" type="text" placeholder="Nombres y apellidos" value="" required>
                                                                                    <br>
                                                                                </div>-->


                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12  ">

                                            <input class="form-control" id="address" name="direccion" type="text" placeholder="Dirección" value="" required><br>
                                        </div>
                                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12  ">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label> Departamento</label>
                                                        <select id="departamento" onChange='cargaContenido(this.id)' name="departamento" class="form-control" required>
                                                            <option value=''>Selecciona Opci&oacute;n...</option> 
                                                            <?php
                                                            $departamento = $this->ListarDepartamentos;
                                                            foreach ($departamento as $indice => $registro) {
                                                                if ($registro['departamento'] == 15) {
                                                                    echo "<option  selected='" . $registro['departamento'] . "' value='" . $registro['departamento'] . "'>" . $registro['descripcion'] . "</option>";
                                                                } else {
                                                                    echo "<option value='" . $registro['departamento'] . "'>" . $registro['descripcion'] . "</option>";
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12  ">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label> Provincia</label>
                                                        <select  name="provincia" id="provincia" onChange='cargaContenido2(this.id, 15)' class="form-control" required>
                                                            <option value=''>Selecciona opci&oacute;n...</option>
                                                            <?php
                                                            $ListarProvincias = $this->ListarProvincias;
                                                            foreach ($ListarProvincias as $indice => $registro) {
                                                                if ($registro['provincia'] == 1) {
                                                                    echo "<option  selected='" . $registro['provincia'] . "' value='" . $registro['provincia'] . "'>" . $registro['descripcion'] . "</option>";
                                                                } else {
                                                                    echo "<option value='" . $registro['provincia'] . "'>" . $registro['descripcion'] . "</option>";
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12  ">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label> Distrito</label>
                                                        <select  name="distrito" id="distrito" class="form-control" required>
                                                            <option value=''>Selecciona opci&oacute;n...</option>
                                                            <?php
                                                            $ListarDistritos = $this->ListarDistritos;
                                                            foreach ($ListarDistritos as $indice => $registro) {
                                                                if ($registro['distrito'] == 40) {
                                                                    echo "<option  selected='" . $registro['distrito'] . "' value='" . $registro['distrito'] . "'>" . $registro['descripcion'] . "</option>";
                                                                } else {
                                                                    echo "<option value='" . $registro['distrito'] . "'>" . $registro['descripcion'] . "</option>";
                                                                }
                                                            }
                                                            ?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                                            <div class="row">
                                                <div class="col-sm-6 col-md-6">
                                                    <input class="form-control" id="fixed" name="fijo" type="text" placeholder="Número fijo" value="" required><br>
                                                </div>
                                                <div class="col-sm-6 col-md-6">
                                                    <input class="form-control" id="mobile" name="celular" type="number" placeholder="Número móvil" value="" ><br>
                                                </div>
                                                <div class="col-md-8 col-sm-12 col-xs-12">
                                                    <input class="form-control" type="email" id="email" name="correo" placeholder="Email" value="" required><br>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <textarea class="form-control" id="subject" name="Subject" rows="8" cols="40" placeholder="Mensaje" ></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 ">
                                    <br>
                                    <button type="submit" class="btn btn-2 btn-2c">Enviar</button>
                                    <!--<div class="success alert-success alert" style="display:none">Su mensaje fue enviado con &eacute;xito.</div>-->
                                    <div class="error alert-danger alert" style="display:none">Su cuenta de E-mail debe ser v&aacute;lida y su mensaje mayor a 100 caracteres.</div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <!-- /Form element row -->
        </div>
    </div>
    <!-- /Contact form -->
</section>